// Generated by dia2code
#ifndef STATE__ABILITIES__H
#define STATE__ABILITIES__H

#include <string>
#include <stdlib.h>

namespace state {

  /// class Abilities - 
  class Abilities {
    // Attributes
  private:
    std::string name_ability;
    int degats_ability;
    int nb_pa;
    int use_distance;
    // Operations
  public:
    Abilities (std::string name, int degats, int nb_pa, int use_dist);
     ~Abilities ();
    std::string getName () const;
    size_t getDegats () const;
    size_t getnb_pa () const;
    void afficheStats () const;
    int getUseDistance () const;
    // Setters and Getters
  };

};

#endif
