// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H

#include <string>
#include <vector>
#include <stdlib.h>

namespace state {
  class Equipment;
  class Abilities;
  class Element;
}

#include "Element.h"
#include "Equipment.h"

namespace state {

  /// class Character - 
  class Character : public state::Element {
    // Associations
    // Attributes
  protected:
    std::string characterClass;
    std::vector<Equipment*> equipment_List;
    std::vector<Abilities*> abilities_List;
    size_t statut;
    bool  player;
    // Operations
  public:
    Character (std::string characterClass);
     ~Character ();
    std::string const getClass () const;
    size_t getPV () const;
    void setPV (int pv);
    size_t getPA () const;
    void setPA (int pa);
    size_t getPM () const;
    void setPM (int pm);
    std::vector<Equipment*> const getEquipmentList ();
    void addEquipment (std::string nom, std::string emplacement, size_t degats);
    void addEquipment (Equipment* equipment);
    void removeEquipment (Equipment* equipment);
    bool const isEquipped (Equipment* equipment_ptr);
    size_t const getStatut ();
    void setStatut (int act_statut);
    std::vector<Abilities*>  getAbilitiesList () const;
    size_t const getDirection () const;
    void setDirection (size_t direction);
    bool const isPlayer ();
    void affiche_Classe ();
    void const affiche_Stats ();
    void const affiche_EquipmentList ();
    virtual void const affiche_AbilitiesList ();
    void const afficheStatut ();
    bool const isObstacle () const;
    bool const isWall () const;
    size_t const getSpaceType () const;
    int getWallType () const;
    int getLandscapeType () const;
    // Setters and Getters
    const std::string& getCharacterClass() const;
    void setCharacterClass(const std::string& characterClass);
    const std::vector<Equipment*>& getEquipment_List() const;
    void setEquipment_List(const std::vector<Equipment*>& equipment_List);
    const std::vector<Abilities*>& getAbilities_List() const;
    void setAbilities_List(const std::vector<Abilities*>& abilities_List);
    const bool & getPlayer() const;
    void setPlayer(const bool & player);
  };

};

#endif
