// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H

#include <stdlib.h>

namespace state {

  // énumération
  /// class Direction - 
  class Direction {
    // Attributes
  public:
    size_t North     = 1;
    size_t East     = 2;
    size_t South     = 3;
    size_t West     = 4;
    // Setters and Getters
  };

};

#endif
