// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H


namespace state {

  // énumération
  /// class Direction - 
  class Direction {
    // Attributes
  public:
    int North     = 1;
    int East     = 2;
    int South     = 3;
    int West     = 4;
    // Setters and Getters
  };

};

#endif
