// Generated by dia2code
#ifndef STATE__EQUIPMENT__H
#define STATE__EQUIPMENT__H

#include <string>

namespace state {

  /// class Equipment - 
  class Equipment {
    // Attributes
  private:
    std::string name_equipment;
    int stats_equipment;
    std::string emplacement_equipment;
    // Operations
  public:
    Equipment (std::string name, std::string emplacement, int stats);
    std::string const getName ();
    std::string const getEmplacement ();
    int const getStats ();
    void affiche_Weapon ();
    // Setters and Getters
  };

};

#endif
