// Generated by dia2code
#ifndef STATE__EQUIPMENT__H
#define STATE__EQUIPMENT__H

#include <string>
#include <stdlib.h>

namespace state {

  /// class Equipment - 
  class Equipment {
    // Attributes
  private:
    std::string name_equipment;
    size_t stats_equipment;
    std::string emplacement_equipment;
    // Operations
  public:
    Equipment (std::string name, std::string emplacement, size_t stats);
    std::string const getName ();
    std::string const getEmplacement ();
    size_t const getStats ();
    void affiche_Weapon ();
    // Setters and Getters
  };

};

#endif
