// Generated by dia2code
#ifndef STATE__LANDSCAPETYPE__H
#define STATE__LANDSCAPETYPE__H


namespace state {

  // énumération
  /// class LandscapeType - 
  class LandscapeType {
    // Attributes
  private:
    int normal     = 0;
    int hauteur_double     = 1;
    // Setters and Getters
  };

};

#endif
