// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class Observer;
  class Event;
}

#include "Event.h"
#include "Observer.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  public:
    std::vector<Observer*> observers;
    // Operations
  public:
    ~Observable ();
    void addObserver (Observer* pobs);
    void removeObserver (Observer* pobs);
    void notify (Event& e);
    // Setters and Getters
  };

};

#endif
