// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H


namespace state {

  /// class Position - 
  class Position {
    // Attributes
  private:
    int x;
    int y;
    // Operations
  public:
    Position (int x = 0, int y = 0);
    void setX (int x);
    void setY (int y);
    int const getX ();
    int const getY ();
    // Setters and Getters
  };

};

#endif
