// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H

#include <stdlib.h>

namespace state {

  /// class Position - 
  class Position {
    // Attributes
  private:
    size_t x;
    size_t y;
    // Operations
  public:
    Position (size_t x = 0, size_t y = 0);
    void setX (size_t x);
    void setY (size_t y);
    size_t const getX ();
    size_t const getY ();
    // Setters and Getters
  };

};

#endif
