// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H

#include <stdlib.h>
#include <string>
#include <vector>

namespace state {
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement {
    // Attributes
  private:
    size_t spaceType;
    // Operations
  public:
    Space (size_t spaceType);
    size_t getSpaceType () const;
    bool isObstacle () const;
    void affiche_Classe ();
    bool isWall () const;
    std::string getClass () const;
    size_t getDirection () const;
    void setDirection (size_t direction);
    int getWallType () const;
    int getLandscapeType () const;
    std::vector<Abilities*> getAbilitiesList ();
    size_t getPV () const;
    size_t getPM () const;
    size_t getPA () const;
    void setPV (int pv);
    void setPM (int pm);
    void setPA (int pa);
    size_t getTypeId () const;
    void setStatut (int statut);
    int getStatut () const;
    int getTeam () const;
    void setTeam (int teamset);
    // Setters and Getters
  };

};

#endif
