// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H

#include <stdlib.h>
#include <string>
#include <vector>

namespace state {
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement {
    // Attributes
  private:
    size_t spaceType;
    // Operations
  public:
    Space (size_t spaceType);
    size_t const getSpaceType () const;
    bool const isObstacle () const;
    void affiche_Classe ();
    bool const isWall () const;
    std::string const getClass () const;
    size_t const getDirection () const;
    void setDirection (size_t direction);
    int getWallType () const;
    int getLandscapeType () const;
    std::vector<Abilities*> getAbilitiesList () const;
    size_t getPV () const;
    size_t getPM () const;
    size_t getPA () const;
    void setPV (int pv);
    void setPM (int pm);
    void setPA (int pa);
    // Setters and Getters
  };

};

#endif
