// Generated by dia2code
#ifndef STATE__SPACETYPEID__H
#define STATE__SPACETYPEID__H

#include <stdlib.h>

namespace state {

  // énumération
  /// class SpaceTypeId - 
  class SpaceTypeId {
    // Attributes
  public:
    size_t Empty     = 1;
    size_t Start     = 2;
    size_t Trap     = 3;
    size_t RedSpace     = 4;
    size_t WhiteSpace     = 5;
    // Setters and Getters
  };

};

#endif
