// Generated by dia2code
#ifndef STATE__SPACETYPEID__H
#define STATE__SPACETYPEID__H


namespace state {

  // énumération
  /// class SpaceTypeId - 
  class SpaceTypeId {
    // Attributes
  public:
    int Empty     = 1;
    int Start     = 2;
    int Trap     = 3;
    // Setters and Getters
  };

};

#endif
