// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H

#include <stdlib.h>

namespace state {
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement {
    // Attributes
  private:
    size_t spaceType;
    // Operations
  public:
    Space (size_t spaceType);
    size_t const getSpaceType ();
    bool const isObstacle ();
    void affiche_Classe ();
    // Setters and Getters
  };

};

#endif
