// Generated by dia2code
#ifndef STATE__STATUT__H
#define STATE__STATUT__H

#include <stdlib.h>

namespace state {

  // énumération
  /// class Statut - 
  class Statut {
    // Attributes
  public:
    size_t normal     = 1;
    size_t poisoned     = 2;
    size_t dead     = 3;
    size_t boosted     = 4;
    size_t wasBoosted     = 5;
    // Setters and Getters
  };

};

#endif
