// Generated by dia2code
#ifndef STATE__STATEETAT__H
#define STATE__STATEETAT__H


namespace state {

  // énumération
  /// class StateEtat - 
  class StateEtat {
    // Attributes
  public:
    int MAIN     = 0;
    int BATTLE     = 1;
    int END     = 2;
    int EXIT     = 3;
    // Setters and Getters
  };

};

#endif
