// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  private:
    ElementTab* carte;
    ElementTab* characters;
    // Operations
  public:
    State (ElementTab* carte);
    ElementTab* getMap () const;
    ElementTab* getCharacters () const;
    // Setters and Getters
  };

};

#endif
