// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  enum StateEventId {
    PVChanged     = 0,
    PMChanged     = 1,
    PAChanged     = 2,
    MapChanged     = 3,
    CharactersChanged     = 4
  };

};

#endif
