// Generated by dia2code
#ifndef STATE__STATICELEMENT__H
#define STATE__STATICELEMENT__H


namespace state {
  class Position;
  class Element;
}

#include "Element.h"

namespace state {

  /// class StaticElement - 
  class StaticElement : public state::Element {
    // Attributes
  protected:
    bool obstacle;
    // Operations
  public:
    StaticElement ();
    ~StaticElement ();
    StaticElement (Position* pos);
    bool const isObstacle ();
    // Setters and Getters
    bool getObstacle() const;
    void setObstacle(bool obstacle);
  };

};

#endif
