// Generated by dia2code
#ifndef STATE__STATUT__H
#define STATE__STATUT__H


namespace state {

  // énumération
  /// class Statut - 
  class Statut {
    // Attributes
  public:
    int normal     = 1;
    int poisoned     = 2;
    int dead     = 3;
    // Setters and Getters
  };

};

#endif
