// Generated by dia2code
#ifndef STATE__TABEVENT__H
#define STATE__TABEVENT__H


namespace state {
  class Event;
  class ElementTab;
}

#include "EventTypeId.h"
#include "Event.h"
#include "ElementTab.h"

namespace state {

  /// class TabEvent - 
  class TabEvent : public state::Event {
    // Associations
    // Attributes
  public:
    int x;
    int y;
    // Operations
  public:
    TabEvent (int x = 0, int y = 0);
    ~TabEvent ();
    EventTypeId getEventType () const;
    // Setters and Getters
  };

};

#endif
