// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  // énumération
  /// class TypeId - 
  class TypeId {
    // Attributes
  private:
    int staticElement     = 0;
    int character     = 1;
    // Setters and Getters
  };

};

#endif
