// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H

#include <stdlib.h>

namespace state {

  // énumération
  /// class TypeId - 
  class TypeId {
    // Attributes
  private:
    size_t staticElement     = 0;
    size_t character     = 1;
    size_t menu     = 2;
    // Setters and Getters
  };

};

#endif
