// Generated by dia2code
#ifndef STATE__WALL__H
#define STATE__WALL__H


namespace state {
  class Obstacle;
}

#include "Obstacle.h"

namespace state {

  /// class Wall - 
  class Wall : public state::Obstacle {
    // Operations
  public:
    Wall ();
    bool const isWall () const;
    bool const isObstacle () const;
    void affiche_Classe ();
    // Setters and Getters
  };

};

#endif
