// Generated by dia2code
#ifndef STATE__WALLTYPEID__H
#define STATE__WALLTYPEID__H

#include <stdlib.h>

namespace state {

  // énumération
  /// class WallTypeId - 
  class WallTypeId {
    // Attributes
  public:
    size_t Normal     = 1;
    size_t Erased     = 2;
    // Setters and Getters
  };

};

#endif
