// Generated by dia2code
#ifndef RENDER__CHARACTERTILESET__H
#define RENDER__CHARACTERTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class CharacterTileSet - 
  class CharacterTileSet : public render::TileSet {
    // Attributes
  protected:
    std::vector<Tile> iop;
    std::vector<Tile> sadida;
    // Operations
  public:
    CharacterTileSet ();
    int const getCellWidth ();
    int const getCellHeight ();
    std::string const getImageFile ();
    const Tile&  getTile (const state::Element& e);
    // Setters and Getters
    const std::vector<Tile>& getIop() const;
    void setIop(const std::vector<Tile>& iop);
    const std::vector<Tile>& getSadida() const;
    void setSadida(const std::vector<Tile>& sadida);
  };

};

#endif
