// Generated by dia2code
#ifndef RENDER__DEBUGLAYER__H
#define RENDER__DEBUGLAYER__H


namespace state {
  class State;
};
namespace render {
  class Layer;
};
namespace state {
  class Observer;
}

#include "Layer.h"
#include "state/Observer.h"

namespace render {

  /// class DebugLayer - 
  class DebugLayer : public render::Layer, public state::Observer {
    // Attributes
  private:
    const state::State& state;
    // Operations
  public:
    DebugLayer (const state::State& state);
    void initSurface ();
    void stateChanged (const state::Event& event);
    void printGridValues (const int* values);
    // Setters and Getters
  };

};

#endif
