// Generated by dia2code
#ifndef RENDER__ELEMENTTABLAYER__H
#define RENDER__ELEMENTTABLAYER__H


namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class ElementTabLayer - 
  class ElementTabLayer : public render::Layer {
    // Attributes
  private:
    const state::ElementTab& tab;
    // Operations
  public:
    ElementTabLayer (const state::ElementTab& tab);
    void initSurface ();
    // Setters and Getters
  };

};

#endif
