// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <stdlib.h>
#include <SFML/Graphics.hpp>

namespace state {
  class State;
};
namespace render {
  class StateLayer;
  class ElementTabLayer;
  class DebugLayer;
};
namespace sf {
  class RenderWindow;
}

#include "StateLayer.h"
#include "ElementTabLayer.h"
#include "DebugLayer.h"
#include "state/State.h"

namespace render {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  private:
    const state::State& state;
    size_t width     = 0;
    size_t height     = 0;
    StateLayer stateLayer;
    ElementTabLayer gridLayer;
    ElementTabLayer charsLayer;
    DebugLayer debugLayer;
    // Operations
  public:
    Scene (const state::State& state);
    size_t getWidth () const;
    size_t getHeight () const;
    void stateChanged (const state::Event& event);
    void draw (sf::RenderWindow& window);
    DebugLayer& getDebugLayer ();
    // Setters and Getters
  };

};

#endif
