// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <stdlib.h>
#include <SFML/Graphics.hpp>

namespace state {
  class State;
};
namespace render {
  class StateLayer;
  class ElementTabLayer;
};
namespace sf {
  class RenderWindow;
}

#include "StateLayer.h"
#include "ElementTabLayer.h"
#include "state/State.h"

namespace render {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  private:
    state::State& state;
    size_t width     = 0;
    size_t height     = 0;
    StateLayer stateLayer;
    ElementTabLayer gridLayer;
    ElementTabLayer MenuLayer;
    ElementTabLayer LandscapeLayer;
    ElementTabLayer WallLayer;
    ElementTabLayer RedLayer;
    ElementTabLayer charsLayer;
    // Operations
  public:
    Scene (state::State& state);
    size_t getWidth () const;
    size_t getHeight () const;
    void stateChanged (const state::Event& event);
    void draw (sf::RenderWindow& window);
    ElementTabLayer& getCharsLayer ();
    ElementTabLayer& getRedLayer ();
    StateLayer& getStateLayer ();
    state::State& getState ();
    ElementTabLayer& getMapLayer ();
    // Setters and Getters
  };

};

#endif
