// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H


namespace state {
  class State;
};
namespace render {
  class Layer;
};
namespace state {
  class Observer;
}

#include "Layer.h"
#include "state/Observer.h"
#include "state/State.h"

namespace render {

  /// class StateLayer - 
  class StateLayer : public render::Layer, public state::Observer {
    // Associations
    // Attributes
  private:
    const state::State& state;
    // Operations
  public:
    StateLayer (const state::State& state);
    void initSurface ();
    void stateChanged (const state::Event& event);
    // Setters and Getters
  };

};

#endif
