// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace render {
  class Tile;
}

namespace render {

  /// class Surface - 
  class Surface {
    // Attributes
  private:
    sf::Texture texture;
    sf::VertexArray quads;
    // Operations
  public:
    Surface ();
    void loadTexture (const std::string& image_file);
    void initQuads (int count);
    void setSpriteLocation (int i, int x, int y);
    void setSpriteTexture (int i, const Tile& texture);
    void const draw (sf::RenderTarget&  target, sf::RenderStates states);
    // Setters and Getters
  };

};

#endif
