// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace render {
  class TileSet;
  class Tile;
};
namespace sf {
  class Drawable;
  class Transformable;
}


namespace render {

  /// class Surface - 
  class Surface : public sf::Drawable, public sf::Transformable {
    // Attributes
  protected:
    sf::Texture texture;
    sf::VertexArray quads;
    // Operations
  public:
    void loadTexture (const std::string& image_file);
    void initQuads (int count);
    void setSpriteLocation (int i, int x, int y, TileSet& tileSet, const state::ElementTab& elmt_tab);
    void setSpriteTexture (int i, const Tile& texture, const state::ElementTab& elmt_tab);
    void draw (sf::RenderTarget&  target, sf::RenderStates states) const;
    const sf::Texture getTexture () const;
    const sf::VertexArray getQuads () const;
    // Setters and Getters
    void setTexture(const sf::Texture& texture);
    void setQuads(const sf::VertexArray& quads);
  };

};

#endif
