// Generated by dia2code
#ifndef AI__DEEPAI__H
#define AI__DEEPAI__H


namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
  class PathMap;
}

#include "state/State.h"
#include "AI.h"
#include "PathMap.h"

namespace ai {

  /// class DeepAI - 
  class DeepAI : public ai::AI {
    // Associations
    // Attributes
  private:
    state::State current_state;
    int updatesCount;
  protected:
    int maxDepth;
    int maxUpdates;
    // Operations
  public:
    DeepAI (const state::State& state);
    void stateChanged ( const state::Event&);
    void run (engine::Engine& engine, int character);
    int minimax_rec (engine::Engine& engine, state::Direction& bestDir, int depth, int character);
    // Setters and Getters
    int getMaxDepth() const;
    void setMaxDepth(int maxDepth);
    int getMaxUpdates() const;
    void setMaxUpdates(int maxUpdates);
  };

};

#endif
