// Generated by dia2code
#ifndef AI__PATHMAP__H
#define AI__PATHMAP__H

#include <vector>
#include <queue>
#include <queue>

namespace ai {
  class Point;
};
namespace state {
  class State;
};
namespace ai {
  class PointCompareWeight;
}

#include "Point.h"
#include "state/State.h"
#include "PointCompareWeight.h"

namespace ai {

  /// class PathMap - 
  class PathMap {
    // Attributes
  private:
    int width     = 0;
    int height     = 0;
    std::vector<int> weights;
    std::priority_queue<Point,std::vector<Point>,PointCompareWeight> queue;
    // Operations
  public:
    int getWeight (const Point& p) const;
    void setWeight (Point& p);
    const int* getWeights () const;
    void init (const state::State& grid, int character);
    void addSink (Point p);
    void update (const state::State& grid, int character);
    std::priority_queue<Point,std::vector<Point>,PointCompareWeight> getQueue () const;
    // Setters and Getters
  };

};

#endif
