// Generated by dia2code
#ifndef AI__RANDOM AI__H
#define AI__RANDOM AI__H

#include <random>

namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class Random AI - 
  class Random AI : public ai::AI {
    // Attributes
  private:
    std::mt19937 randgen;
    // Operations
  public:
    void run (engine::Engine& engine, int character);
    void RandomAI (int randomSeed);
    // Setters and Getters
  };

};

#endif
