// Generated by dia2code
#ifndef AI__RANDOM_AI__H
#define AI__RANDOM_AI__H

#include <random>

namespace engine {
  class Engine;
};
namespace state {
  class State;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class Random_AI - 
  class Random_AI : public ai::AI {
    // Attributes
  private:
    std::mt19937 randgen;
    // Operations
  public:
    Random_AI (int randomSeed);
    void run (engine::Engine& engine, int character, state::State& state);
    // Setters and Getters
  };

};

#endif
