// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    LOAD     = 1,
    DIRECTION     = 2,
    MOVE_CHARACTER     = 3,
    LIFE     = 4,
    ATTACK     = 5,
    SURBRILLANCE     = 6,
    WHITESURBRILLANCE     = 7
  };

};

#endif
