// Generated by dia2code
#ifndef ENGINE__ENGINE_OBSERVER__H
#define ENGINE__ENGINE_OBSERVER__H


namespace engine {

  /// class Engine_Observer - 
  class Engine_Observer {
    // Operations
  public:
    void engineUpdating ();
    void engineUpdated ();
    // Setters and Getters
  };

};

#endif
