// Generated by dia2code
#ifndef ENGINE__ENGINE_OBSERVABLE__H
#define ENGINE__ENGINE_OBSERVABLE__H

#include <vector>

namespace engine {
  class Engine_Observer;
}

#include "Engine_Observer.h"

namespace engine {

  /// class Engine_Observable - 
  class Engine_Observable {
    // Associations
    // Attributes
  private:
    mutable std::vector<Engine_Observer*> observers;
    // Operations
  public:
    ~Engine_Observable ();
    void registerObserver (Engine_Observer* o) const;
    void notifyUpdating () const;
    void notifyUpdated () const;
    // Setters and Getters
  };

};

#endif
