// Generated by dia2code
#ifndef ENGINE__ENGINE_OBSERVER__H
#define ENGINE__ENGINE_OBSERVER__H


namespace engine {

  /// class Engine_Observer - 
  class Engine_Observer {
    // Operations
  public:
    virtual void engineUpdating () = 0;
    virtual void engineUpdated ( ) = 0;
    // Setters and Getters
  };

};

#endif
