// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <map>
#include <memory>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  private:
    state::State* currentState;
    std::map<int,std::unique_ptr<Command>> currentCommands;
    // Operations
  public:
    Engine ();
    ~Engine ();
    void setState (state::State* state);
    const state::State& getState () const;
    void addPassiveCommands ();
    void addCommand (int priority, Command* cmd);
    void addCommand (int priority, std::unique_ptr<Command> cmd);
    int getNbCommands () const;
    void update ();
    // Setters and Getters
  };

};

#endif
