// Generated by dia2code
#ifndef ENGINE__HANDLESTATUT__H
#define ENGINE__HANDLESTATUT__H

#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class HandleStatut - 
  class HandleStatut : public engine::Command {
    // Attributes
  public:
    int character;
    // Operations
  public:
    HandleStatut (int chara);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    Json::Value serialize ();
    void deserialize (Json::Value cmd);
    // Setters and Getters
  };

};

#endif
