// Generated by dia2code
#ifndef ENGINE__HANDLEABILITIESCOMMAND__H
#define ENGINE__HANDLEABILITIESCOMMAND__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class HandleAbilitiesCommand - 
  class HandleAbilitiesCommand : public engine::Command {
    // Attributes
  protected:
    int character;
    std::vector<state::Abilities> abilities_List;
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    int getCharacter() const;
    void setCharacter(int character);
    const std::vector<state::Abilities>& getAbilities_List() const;
    void setAbilities_List(const std::vector<state::Abilities>& abilities_List);
  };

};

#endif
