// Generated by dia2code
#ifndef ENGINE__HANDLECOLLISIONSCOMMAND__H
#define ENGINE__HANDLECOLLISIONSCOMMAND__H


namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class HandleCollisionsCommand - 
  class HandleCollisionsCommand : public engine::Command {
    // Setters and Getters
  };

};

#endif
