// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H

#include <string>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class LoadCommand - 
  class LoadCommand : public engine::Command {
    // Attributes
  protected:
    std::string fileName;
    // Operations
  public:
    LoadCommand (const char* f);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    ~LoadCommand ();
    // Setters and Getters
    const std::string& getFileName() const;
    void setFileName(const std::string& fileName);
  };

};

#endif
