// Generated by dia2code
#ifndef ENGINE__ORIENTATIONCOMMAND__H
#define ENGINE__ORIENTATIONCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
};
namespace state {
  class Direction;
}

#include "CommandTypeId.h"
#include "Command.h"
#include "state/Direction.h"

namespace engine {

  /// class OrientationCommand - 
  class OrientationCommand : public engine::Command {
    // Associations
    // Attributes
  protected:
    int character;
    int direction;
    // Operations
  public:
    OrientationCommand (int character, int direction);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    ~OrientationCommand ();
    // Setters and Getters
    int getCharacter() const;
    void setCharacter(int character);
    int getDirection() const;
    void setDirection(int direction);
  };

};

#endif
