// Generated by dia2code
#ifndef ENGINE__SURBRILLANCECOMMAND__H
#define ENGINE__SURBRILLANCECOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class SurbrillanceCommand - 
  class SurbrillanceCommand : public engine::Command {
    // Attributes
  public:
    int x_mouse_iso;
    int y_mouse_iso;
    // Operations
  public:
    SurbrillanceCommand (int x, int y);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
