// Generated by dia2code
#ifndef ENGINE__SURBRILLANCECOMMAND__H
#define ENGINE__SURBRILLANCECOMMAND__H

#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Engine;
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class SurbrillanceCommand - 
  class SurbrillanceCommand : public engine::Command {
    // Attributes
  public:
    int x_mouse_iso;
    int y_mouse_iso;
    // Operations
  public:
    SurbrillanceCommand (int x, int y);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    void execute (state::State& state, engine::Engine& engine);
    Json::Value serialize ();
    void deserialize (Json::Value cmd);
    // Setters and Getters
  };

};

#endif
