// Generated by dia2code
#ifndef ENGINE__TURNSURBRILLANCECOMMAND__H
#define ENGINE__TURNSURBRILLANCECOMMAND__H

#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class TurnSurbrillanceCommand - 
  class TurnSurbrillanceCommand : public engine::Command {
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    Json::Value serialize ();
    void deserialize (Json::Value cmd);
    // Setters and Getters
  };

};

#endif
