// Generated by dia2code
#ifndef ENGINE__TURNCOMMAND__H
#define ENGINE__TURNCOMMAND__H

#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class TurnCommand - 
  class TurnCommand : public engine::Command {
    // Operations
  public:
    TurnCommand (state::State& state);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    Json::Value serialize ();
    void deserialize (Json::Value cmd);
    // Setters and Getters
  };

};

#endif
