// Generated by dia2code
#ifndef ENGINE__TURNCOMMAND__H
#define ENGINE__TURNCOMMAND__H


namespace state {
  class State;
}

#include "CommandTypeId.h"

namespace engine {

  /// class TurnCommand - 
  class TurnCommand {
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
