// Generated by dia2code
#ifndef SERVER__SERVICEEXCEPTION__H
#define SERVER__SERVICEEXCEPTION__H

#include <string>

namespace server {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace server {

  /// class ServiceException - 
  class ServiceException {
    // Associations
    // Attributes
  protected:
    std::string msg;
    HttpStatus status;
    // Operations
  public:
    ServiceException (HttpStatus status, std::string msg);
    HttpStatus getStatus () const;
    const char* what () const;
    // Setters and Getters
    const std::string& getMsg() const;
    void setMsg(const std::string& msg);
    void setStatus(HttpStatus status);
  };

};

#endif
