// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeId.h"
#include "engine/Command.h"
#include "engine/LoadCommand.h"
#include "engine/MoveCharacterCommand.h"
#include "engine/OrientationCommand.h"
#include "engine/Engine.h"
#include "engine/LifeCommand.h"
#include "engine/AttackCommand.h"
#include "engine/SurbrillanceCommand.h"
#include "engine/WhiteSurbrillanceCommand.h"
#endif
