// Generated by dia2code
#ifndef ENGINE__MOUSEMOVEDCOMMAND__H
#define ENGINE__MOUSEMOVEDCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Engine;
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class MouseMovedCommand - 
  class MouseMovedCommand : public engine::Command {
    // Attributes
  private:
    int x_mouse;
    int y_mouse;
    // Operations
  public:
    MouseMovedCommand (int x, int y);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    void execute (state::State& state, engine::Engine& engine);
    // Setters and Getters
  };

};

#endif
