// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <memory>
#include <mutex>

namespace engine {
  class Engine;
};
namespace ai {
  class AI;
};
namespace render {
  class Scene;
}

#include "engine/Engine.h"
#include "ai/AI.h"
#include "render/Scene.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  private:
    engine::Engine engine;
    std::unique_ptr<ai::AI> characters_ai;
    mutable std::mutex draw_mutex;
    // Operations
  public:
    Client ();
    void engineUpdating ();
    void engineUpdated ();
    void run ();
    // Setters and Getters
  };

};

#endif
